server:
  port: 8761

spring:
  application:
    name: discovery-service
  boot:
    admin:
      client:
        url: http://localhost:7777/admin

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"